package ru.mos.efp.efp.drools.ege;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlStatusOk implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public XmlStatusOk() {
    }

}